# world.ac Jekyll Config File.
# Careful messing with this if you don't know what it means! Find out more at jekyllrb.com
# Last Major Release: 3.0.0

# General Site Build Settings
title: World Affairs Conference
description: The website for the World Affairs Conference, Canada's oldest student-led current affairs conference that explores world issues relevant to youth.
baseurl: ""
url: "world.ac"
regurl: "https://reg.world.ac"
github: "https://github.com/worldaffairsconference/world.ac"

# Social Accounts
email: mailto:wac@ucc.on.ca
facebook: https://www.facebook.com/worldaffairsconference/
instagram: "https://instagram.com/WorldAffairsCon"
twitter: https://twitter.com/WorldAffairsCon

# Build Settings
markdown: kramdown

# Rendered Collections
collections:
  plenaries:
    output: true
    layout: plenary

# Excludes
exclude:
  - vendor/bundle
  - ".travis.yml"
  - README.md
  - "*.sh"
  - Gemfile
  - Gemfile.lock
  - Rakefile
